#!/bin/bash

BLOCK_SIZE=2048
NUM_INSTANCES_TRAIN=200

WALL_DENSITIESS_TRAIN='
    wd-0.4
'

##

WIDTH_HEIGHT=4

NUM_SIMULATIONS_TRAIN=50
MAX_TREE_DEPTH_TRAIN=40
NUM_SIMULATIONS_TEST=50
MAX_TREE_DEPTH_TEST=40

WALL_DENSITY_TEST=0.4

for WALL_DENSITIES_TRAIN in $WALL_DENSITIESS_TRAIN
do
    echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST

    source sample_navigation_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST
    sleep 1s
done

WALL_DENSITY_TEST=0.3

for WALL_DENSITIES_TRAIN in $WALL_DENSITIESS_TRAIN
do
    echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST

    source sample_navigation_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST
    sleep 1s
done

WALL_DENSITY_TEST=0.2

for WALL_DENSITIES_TRAIN in $WALL_DENSITIESS_TRAIN
do
    echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST

    source sample_navigation_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST
    sleep 1s
done

WALL_DENSITY_TEST=0.1

for WALL_DENSITIES_TRAIN in $WALL_DENSITIESS_TRAIN
do
    echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST

    source sample_navigation_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $WIDTH_HEIGHT $WALL_DENSITIES_TRAIN $WALL_DENSITY_TEST $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST
    sleep 1s
done