#!/bin/bash

BLOCK_SIZE=2048
NUM_INSTANCES_TRAIN=200
TEMPERATURE=0.8

##

NUM_ARMS=2
MAX_DEPTHS='6 8'
NUM_GOALSS='4 8'

NUM_SIMULATIONS_TRAIN=50
MAX_TREE_DEPTH_TRAIN=10
NUM_SIMULATIONS_TEST=50
MAX_TREE_DEPTH_TEST=10

for NUM_GOALS in $NUM_GOALSS
do
    for MAX_DEPTH in $MAX_DEPTHS
    do
        NUM_ARMS_TRAIN=$NUM_ARMS
        NUM_ARMS_TEST=$NUM_ARMS

        NUM_GOALS_TRAIN=$NUM_GOALS
        NUM_GOALS_TEST=$NUM_GOALS

        echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE

        source sample_tree_search_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE
        sleep 1s
    done
done

##

NUM_ARMS=4
MAX_DEPTHS='4'
NUM_GOALSS='4 8'

NUM_SIMULATIONS_TRAIN=50
MAX_TREE_DEPTH_TRAIN=10
NUM_SIMULATIONS_TEST=50
MAX_TREE_DEPTH_TEST=10

for NUM_GOALS in $NUM_GOALSS
do
    for MAX_DEPTH in $MAX_DEPTHS
    do
        NUM_ARMS_TRAIN=$NUM_ARMS
        NUM_ARMS_TEST=$NUM_ARMS

        NUM_GOALS_TRAIN=$NUM_GOALS
        NUM_GOALS_TEST=$NUM_GOALS

        echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE

        source sample_tree_search_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE
        sleep 1s
    done
done

##

NUM_ARMS=2
MAX_DEPTH=6
NUM_GOALS_TRAIN=8
NUM_GOALSS_TEST='2 4'

NUM_SIMULATIONS_TRAIN=50
MAX_TREE_DEPTH_TRAIN=10
NUM_SIMULATIONS_TEST=50
MAX_TREE_DEPTH_TEST=10

for NUM_GOALS_TEST in $NUM_GOALSS_TEST
do
    NUM_ARMS_TRAIN=$NUM_ARMS
    NUM_ARMS_TEST=$NUM_ARMS

    echo $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE

    source sample_tree_search_single.sh $BLOCK_SIZE $NUM_INSTANCES_TRAIN $NUM_GOALS_TRAIN $NUM_GOALS_TEST $NUM_ARMS_TRAIN $NUM_ARMS_TEST $MAX_DEPTH $NUM_SIMULATIONS_TRAIN $NUM_SIMULATIONS_TEST $MAX_TREE_DEPTH_TRAIN $MAX_TREE_DEPTH_TEST $TEMPERATURE
    sleep 1s
done