#!/bin/bash

BLOCK_SIZE=2048
NUM_INSTANCES=200

WALL_DENSITIESS='
    wd-0.4
'

##

WIDTH_HEIGHT=4
NUM_SIMULATIONS=50
MAX_TREE_DEPTH=40

for WALL_DENSITIES in $WALL_DENSITIESS
do
    echo $BLOCK_SIZE $NUM_INSTANCES $WIDTH_HEIGHT $WALL_DENSITIES $NUM_SIMULATIONS $MAX_TREE_DEPTH

    source train_navigation_single.sh $BLOCK_SIZE $NUM_INSTANCES $WIDTH_HEIGHT $WALL_DENSITIES $NUM_SIMULATIONS $MAX_TREE_DEPTH
    sleep 1s
done